#!/bin/bash -eu
PYTHON=python
QUEUES="pending running ok failed canceled"

init() {
    # make queue directories
    env=$1
    mkdir -vp $env/queue
    for path in $QUEUES; do
        mkdir -v $env/queue/$path
    done
    mkdir -vp $env/tmp
    echo "init ok"
}

sync() {
    $(dirname $0)/sync_ks.sh "$@"
}

run() {
    $PYTHON $(dirname $0)/run_ks.py "$@"
}

status() {
    echo "queue length"
    for q in $(find queue -maxdepth 1 -mindepth 1 -type d); do
        printf "%8s: %d\n" $(basename $q) $(ls $q|wc -l 2>/dev/null)
    done
}

usage() {
    echo "Control script to download ks and run mic automatically"
    echo "Usage: $0 [-h|--help] ACTION [options]"
    echo
    echo "Available ACTIONs:"
    echo "  init <env>"
    echo "    echo make an env for following steps"
    echo "  sync"
    echo "    download ks from remote repo and push into queue"
    echo "  run"
    echo "    for each ks in queue to run mic"
    echo "  status"
    echo "    display status for all queues"
    echo "  go"
    echo "    shortcut for sync && run"
}


#### Main
if [ $# -lt 1 ]; then
    usage
    exit 0
fi

action=$1
shift

case $action in
    init)
        if [ $# -lt 1 ]; then
            echo "env parameter is required"
            exit 1
        fi
        init "$1"
        ;;
    sync)
        sync "$@"
        ;;
    run)
        run "$@"
        ;;
    status)
        status "$@"
        ;;
    go)
        sync && run
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        echo "Invalid action: $action"
        exit 1
        ;;
esac